package com.atc.osee.web.folio;

public interface FolioConstants {
	
	final String FOLIO_URL_BACKEND = "folio-url-backend";
	final String FOLIO_URL_FRONTEND = "folio-url-frontend";
	final String FOLIO_USER = "folio-user";
	final String FOLIO_PASS = "folio-pass";	
	final String FOLIO_TENANT = "folio-tenant";
	final String NOTE_NOTE_ID="NOTE_NOTE_ID";
	final String NOTE_NOTE_DESC="NOTE_NOTE_DESC"; 
					
	final String NOTE_BIRTH_LOCATION_ID="NOTE_BIRTH_LOCATION_ID";
	final String NOTE_BIRTH_LOCATION_DESC="NOTE_BIRTH_LOCATION_DESC";
				
	final String NOTE_NATION_ID="NOTE_NATION_ID";
	final String NOTE_NATION_DESC="NOTE_NATION_DESC";
				
	final String NOTE_RESIDENCE_PERMISSION_ID="NOTE_RESIDENCE_PERMISSION_ID";
	final String NOTE_RESIDENCE_PERMISSION_DESC="NOTE_RESIDENCE_PERMISSION_DESC";
				
	final String NOTE_GENDER_ID="NOTE_GENDER_ID";
	final String NOTE_GENDER_DESC="NOTE_GENDER_DESC";
				
	final String NOTE_DOCUMENT_ID="NOTE_DOCUMENT_ID";
	final String NOTE_DOCUMENT_DESC="NOTE_DOCUMENT_DESC";
				
	final String NOTE_JOB_ID="NOTE_JOB_ID";
	final String NOTE_JOB_DESC="NOTE_JOB_DESC";
				
	final String NOTE_GUARDIAN_ID="NOTE_GUARDIAN_ID";
	final String NOTE_GUARDIAN_DESC="NOTE_GUARDIAN_DESC";
				
	final String NOTE_TAG_RFID_ID="NOTE_TAG_RFID_ID";
	final String NOTE_TAG_RFID_DESC="NOTE_TAG_RFID_DESC";
	
	final String USER_BASE = "USER_BASE"; //Ut: Base
	final String USER_PREREG = "USER_PREREG"; //Ut: preregistrato	
	final String USER_BASE_LOAN = "USER_BASE_LOAN"; // Ut: base + Prestito	
	final String USER_MUSIC_LOAN = "USER_MUSIC_LOAN"; // Ut: Sala Consultazione e Musica+Prestito
	final String USER_MUSIC = "USER_MUSIC"; // Ut: Sala Consultazione e Musica
	final String USER_HANDWRITE_LOAN = "USER_HANDWRITE_LOAN"; // Ut: Sala Manoscritti+Prestito
	final String USER_HANDWRITE = "USER_HANDWRITE"; // Ut: Sala Manoscritti
	final String USER_STAFF = "USER_STAFF"; // Ut:Personale interno
	final String USER_ADMIN = "USER_ADMIN"; // Ut: Admin
	final String USER_VISIT = "USER_VISIT"; // Ut: Visitatore
	
	final String PAGE_REQUEST = "PAGE_REQUEST";
	final String HOLD_REQUEST = "HOLD_REQUEST";
	
	final String AVAILABLE = "AVAILABLE";
	final String STATUS_PAGED = "STATUS_PAGED";
	final String STATUS_CLOSED_CANCELLED = "STATUS_CLOSED_CANCELLED";
	final String STATUS_CHECKED_OUT = "STATUS_CHECKED_OUT";
	final String STATUS_OPEN_LOAN = "STATUS_OPEN_LOAN";
	final String DELETE_BY_PATRON_REASON_ID = "DELETE_BY_PATRON_REASON_ID";
			
	final String LOAN_TYPE_LOAN_ID = "LOAN_TYPE_LOAN_ID";
	final String LOAN_TYPE_LOAN_DESCR = "LOAN_TYPE_LOAN_DESCR";
	final String LOAN_TYPE_CONS_ID = "LOAN_TYPE_CONS_ID";
	final String LOAN_TYPE_CONS_DESCR = "LOAN_TYPE_CONS_DESCR";
	
	final String TEMPORARY_LOCATION_STORAGE_AREA_ID = "TEMPORARY_LOCATION_STORAGE_AREA_ID";
	final String TEMPORARY_LOCATION_STORAGE_AREA_DESCR = "TEMPORARY_LOCATION_STORAGE_AREA_DESCR";
	
	final String MONOG_MOD_PREST_CODE = "MONOG_MOD_PREST_CODE"; // monografia moderna prestabile
	final String MONOG_AN_NOT_PREST_CODE = "MONOG_AN_NOT_PREST_CODE"; // monografia antica o rara prestito escluso
	final String SERIAL_MOD_CODE = "SERIAL_MOD_CODE"; // rivista moderna
	final String SERIAL_AN_CODE = "SERIAL_AN_CODE"; // rivista antica o rara
	final String MUSIC_CODE = "MUSIC_CODE"; // magazzino musica
	final String JOURNAL_CODE = "JOURNAL_CODE"; // giornali
	final String HANDWRITE_CODE = "HANDWRITE_CODE"; // manoscritti e rari
	final String THESIS_CODE = "THESIS_CODE"; //# lettura tesi in sede
	final String MICROFILM_CODE = "MICROFILM_CODE"; // lettura microfilm
	final String ELETRONIC_CODE = "ELETRONIC_CODE"; // risorsa elettronica

	final String MUSIC_ROOM = "MUSIC_ROOM"; // Sala Musica
	final String MUSIC_ROOM_DESC = "MUSIC_ROOM_DESC";
	final String HANDWRITE_ROOM = "HANDWRITE_ROOM"; // Sala Manoscritti
	final String HANDWRITE_ROOM_DESC = "HANDWRITE_ROOM_DESC";
	final String CONSULT_ROOM = "CONSULT_ROOM"; // Sala Consultazione
	final String CONSULT_ROOM_DESC = "CONSULT_ROOM_DESC";
	final String READ_ROOM = "READ_ROOM"; // Sala Lettura
	final String READ_ROOM_DESC = "READ_ROOM_DESC";
	final String SERIAL_ROOM = "SERIAL_ROOM"; // Sala Periodici
	final String SERIAL_ROOM_DESC = "SERIAL_ROOM_DESC";
	final String LOAN_ROOM = "LOAN_ROOM"; // Sala Prestito 
	final String LOAN_ROOM_DESC = "LOAN_ROOM_DESC";
	
	final String ID_BID  ="ID_BID"; // bid di SBN
	final String ID_ISBN ="ID_ISBN"; // ISBN valido (sono esclusi gli errati)
	final String ID_ISSN ="ID_ISSN"; // ISSN valido (sono esculsi gli errati)
	final String ID_DOI  ="ID_DOI"; // DOI
	
	final String MONOG_MOD_PREST_ID = "MONOG_MOD_PREST_ID";  // A
	final String RESOURCE_NOT_AVAIL_ID = "RESOURCE_NOT_AVAIL_ID"; // K
	final String THESIS_ID = "THESIS_ID"; // L
	final String JOURNAL_ID = "JOURNAL_ID"; // G
	final String SERIAL_MOD_ID = "SERIAL_MOD_ID"; // D
	final String ELETRONIC_ID = "ELETRONIC_ID"; // R
	final String SERIAL_AN_ID = "SERIAL_AN_ID"; // E 
	final String MONOG_AN_NOT_PREST_ID = "MONOG_AN_NOT_PREST_ID"; // C
	final String HANDWRITE_ID = "HANDWRITE_ID"; // H
	final String MUSIC_ID = "MUSIC_ID"; // F
	final String MONOG_MOD_NOT_PREST_ID = "MONOG_MOD_NOT_PREST_ID"; // B
	final String MICROFILM_ID = "MICROFILM_ID"; // M
	
	final String RESIDENCE_ADDRESS = "RESIDENCE_ADDRESS";
	final String DOMICILE_ADDRESS = "DOMICILE_ADDRESS";
	
	final String MAIN_ADDRESS_RESIDENCE = "MAIN_ADDRESS_RESIDENCE";
	final String MAIN_ADDRESS_DOMICILE = "MAIN_ADDRESS_DOMICILE";
	
	final String BIBLIO_PROFILE_PERMISSION = "BIBLIO_PROFILE_PERMISSION";
	final String FOLIO_ADMIN_PROFILE_PERMISSION = "FOLIO_ADMIN_PROFILE_PERMISSION";
	final String ADMIN_BNCF_PROFILE_PERMISSION = "ADMIN_BNCF_PROFILE_PERMISSION";
	final String STATUS_OTHER_LOCALE = "STATUS_OTHER_LOCALE";
	final String AUTHOR_CORPORATE_TYPE = "AUTHOR_CORPORATE_TYPE";
	final String AUTHOR_PERSON_TYPE = "AUTHOR_PERSON_TYPE";
	final String GENERALE_NOTE_TYPE = "GENERALE_NOTE_TYPE";
	
	final String SOURCE_OPAC = "OPAC";
	
	final String TYPE_MONOGRAPH = "TYPE_MONOGRAPH";
	final String TYPE_PERIODIC = "TYPE_PERIODIC";
	
	final String TYPE_RESOURCE_MONOGRAPH = "TYPE_RESOURCE_MONOGRAPH";
	final String TYPE_RESOURCE_PERIODIC = "TYPE_RESOURCE_PERIODIC";
	final String TYPE_RESOURCE_MANUSCRIPT = "TYPE_RESOURCE_MANUSCRIPT";
	final String TYPE_HOLDING_MONOGRAPH = "TYPE_HOLDING_MONOGRAPH";
	final String TYPE_HOLDING_PERIODIC = "TYPE_HOLDING_PERIODIC";
	final String SECTION_HOLDING_A = "SECTION_HOLDING_A";
	final String SECTION_HOLDING_H = "SECTION_HOLDING_H";
	final String SECTION_HOLDING_G = "SECTION_HOLDING_G";
	final String SECTION_HOLDING_C = "SECTION_HOLDING_C";
	final String SECTION_HOLDING_D = "SECTION_HOLDING_D";
	final String SECTION_HOLDING_E = "SECTION_HOLDING_E";
	final String SECTION_HOLDING_F = "SECTION_HOLDING_F";
	final String SECTION_HOLDING_K = "SECTION_HOLDING_K";
	final String SECTION_HOLDING_L = "SECTION_HOLDING_L";
	final String SECTION_HOLDING_M = "SECTION_HOLDING_M";
	final String SECTION_HOLDING_R = "SECTION_HOLDING_R";
	
	// ####### barcode prefix ########
	final String MONOGRAPH_AND_SERIAL_PREFIX = "PRE";
	final String MANUSCRIPT_PREFIX = "MSC";
	final String SERIAL_OPAC_PREFIX = "SRL";
	
	final String BID_TYPE_SBNWEB = "bid";
	
	// ###### Printing point ########
	final String PRINTING_POINT_SLETTURA = "slettura";
	final String PRINTING_POINT_SCONSULTAZIONE = "sconsultazione";
	final String PRINTING_POINT_SMUSICA = "smusica";
	final String PRINTING_POINT_SMANOSCRITTI = "smanoscritti";
	final String PRINTING_POINT_SPERIODICI = "speriodici";
	
	final String QUARANTINE = "QUARANTINE";
	
	//custom field
	final String CUSTOM_FIELD_GENDER= "CUSTOM_FIELD_GENDER";
	final String CUSTOM_FIELD_JOB="CUSTOM_FIELD_JOB";
	final String CUSTOM_FIELD_GUARDIAN="CUSTOM_FIELD_GUARDIAN";
	final String CUSTOM_FIELD_TYPE_DOCUMENT_GUARDIAN="CUSTOM_FIELD_TYPE_DOCUMENT_GUARDIAN";
	final String CUSTOM_FIELD_NUMBER_DOCUMENT_GUARDIAN="CUSTOM_FIELD_NUMBER_DOCUMENT_GUARDIAN";
	final String CUSTOM_FIELD_EXPIRATION_GUARDIAN="CUSTOM_FIELD_EXPIRATION_GUARDIAN";
	final String CUSTOM_FIELD_RELEASEDBY_GUARDIAN_DOCUMENT="CUSTOM_FIELD_RELEASEDBY_GUARDIAN_DOCUMENT";
	final String CUSTOM_FIELD_NATION="CUSTOM_FIELD_NATION";
	final String CUSTOM_FIELD_COUNTRY_OF_BIRTH="CUSTOM_FIELD_COUNTRY_OF_BIRTH";
	final String CUSTOM_FIELD_BIRTHPLACE="CUSTOM_FIELD_BIRTHPLACE";
	final String CUSTOM_FIELD_PROVINCE_OF_BIRTH="CUSTOM_FIELD_PROVINCE_OF_BIRTH";
	final String CUSTOM_FIELD_EXPIRATION_RESIDENCE_PERMISSION="CUSTOM_FIELD_EXPIRATION_RESIDENCE_PERMISSION";
	final String CUSTOM_FIELD_RESIDENCE_PERMISSION_NUMBER="CUSTOM_FIELD_RESIDENCE_PERMISSION_NUMBER";
	final String CUSTOM_FIELD_TYPE_DOCUMENT="CUSTOM_FIELD_TYPE_DOCUMENT";
	final String CUSTOM_FIELD_NUMBER_DOCUMENT="CUSTOM_FIELD_NUMBER_DOCUMENT";
	final String CUSTOM_FIELD_RELEASEDBY="CUSTOM_FIELD_RELEASEDBY";
	final String CUSTOM_FIELD_EXPIRATION_DOCUMENT="CUSTOM_FIELD_EXPIRATION_DOCUMENT";
	final String CUSTOM_FIELD_REPRODUCTION_RULES="CUSTOM_FIELD_REPRODUCTION_RULES";
	final String CUSTOM_FIELD_DATA_PROCESSING="CUSTOM_FIELD_DATA_PROCESSING";
	
	
	
	
}
